### PR TITLE
best the_post_thumbnail and post exerpt alignment

### PR DESCRIPTION
**Pull request by semteacher**

### CODE REVIEW

**Comment by mkrdip** [comment]
Hi @semteacher, 

Thanks for the pull. This will be added to latest release of this plugin. 

Have a nice day, Cheers!

**Comment by mkrdip** [comment]
Hey @DanielFloeter, 

What is you say about this pull request? :)

**Comment by DanielFloeter** [comment]
I use .cat-post-thumbnail img{ margin-bottom: 5px; } (0af0729c58a9c12264aadf95a821b763c64c1e2f)

For the other code I think less CSS as possible. No CSS which users have to override it later.

And please no typing errors in a pull request (.post-thumbail = > .post-thumbnail) ;(

@semteacher : Please give use a little more information what the code is for and what it will do. Then we can better decide If? and How? we will implement it. I'll hope you're back soon.

**Comment by semteacher** [comment]
Hi @DanielFloeter and @mkrdip 
My pull request was provided before your (0af0729) commit
A has problem on my WP site (http://www.tdmu.edu.ua/) where category post items slides and  partially covered one another. It happens when description was very short... I was solved it with additional "div" block and <p> in my code... 
But as I can see now your last updates (0af0729) provide the same result but more efficiently via CSS:
.cat-post-item:before, 
.cat-post-item:after {
	content: "";
	display: table;
}
So I will close this pull request...

**Comment by DanielFloeter** [comment]
Hello @semteacher ,
thanks for your help. That was a bug that had to be gefixet!

Give us a hint and feel free, if you had problems and how we can fix it or we will discuss about issuses of course on Gitter (https://gitter.im/mkrdip/category-posts-widget).

best Regards
Daniel

**Comment by semteacher** [comment]
Hello @DanielFloeter 
Thanks for your attention
There are no more problems with this widget. Hour ago i was replace my mods with last master branch code. And everything still working fine!

**Pull request closed without merging**
